config/routes.rb
Rails.application.routes.draw do
  resources :items
  resources :menus
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :menu, optional: true
  validates :name, presence: true
  validates :price, presence: true
  validates :description, presence: true
  
end

app/models/menu.rb
class Menu < ApplicationRecord
  has_many :items
  validates :name, presence: true
  validates :name, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  # GET /items
  # GET /items.json
  def index
    if params[:search]
      @items = Item.where('name ILIKE ?', "%#{params[:search]}%")
    else
      @items = Item.all
    end
  end

  # GET /items/1
  # GET /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def item_params
      params.require(:item).permit(:name, :price, :description, :image_url, :menu_id, :search)
    end
end

app/controllers/menus_controller.rb
class MenusController < ApplicationController
  before_action :set_menu, only: [:show, :edit, :update, :destroy]

  # GET /menus
  # GET /menus.json
  def index
    @menus = Menu.all
  end

  # GET /menus/1
  # GET /menus/1.json
  def show
  end

  # GET /menus/new
  def new
    @menu = Menu.new
  end

  # GET /menus/1/edit
  def edit
  end

  # POST /menus
  # POST /menus.json
  def create
    @menu = Menu.new(menu_params)

    respond_to do |format|
      if @menu.save
        format.html { redirect_to @menu, notice: 'Menu was successfully created.' }
        format.json { render :show, status: :created, location: @menu }
      else
        format.html { render :new }
        format.json { render json: @menu.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /menus/1
  # PATCH/PUT /menus/1.json
  def update
    respond_to do |format|
      if @menu.update(menu_params)
        format.html { redirect_to @menu, notice: 'Menu was successfully updated.' }
        format.json { render :show, status: :ok, location: @menu }
      else
        format.html { render :edit }
        format.json { render json: @menu.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /menus/1
  # DELETE /menus/1.json
  def destroy
    @menu.destroy
    respond_to do |format|
      format.html { redirect_to menus_url, notice: 'Menu was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_menu
      @menu = Menu.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def menu_params
      params.require(:menu).permit(:name)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/items/_form.html.erb
<div class="container">
  <div class="row">
    <div class="col">
      <%= form_with(model: item) do |form| %>
        <% if item.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(item.errors.count, "error") %> prohibited this item from being saved:</h2>

            <ul>
              <% item.errors.each do |error| %>
                <li><%= error.full_message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>

        <div class="md-6 pb-3">
          <%= form.text_field :name, class: "form-control", placeholder: :name %>
        </div>

        <div class="md-6 pb-3">
          <%= form.text_field :price, class: "form-control", placeholder: :price %>
        </div>

        <div class="md-6 pb-3">
          <%= form.text_area :description, class: "form-control", placeholder: :description %>
        </div>

        <div class="md-6 pb-3">
          <%= form.text_field :image_url, class: "form-control", placeholder: :image_url %>
        </div>

        <div class="md-6 pb-3">
          <%= form.collection_select :menu, Menu.all, :id, :name, include_blank: true , class: "form-control" %>
        </div>

        <div class="actions pt-3 pb-3">
          <%= form.submit %>
        </div>
      <% end %>

    </div>
  </div>
</div>

app/views/items/edit.html.erb
<h1>Editing Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<p id="notice"><%= notice %></p>

<div class="card-group">
  <div class="row">
  <% @items.each do |item| %>
  <div class="col pb-3">
    <div class="card border-dark text-white bg-dark mb-3 h-100" style="width: 18rem;">
      <%= image_tag("#{item.image_url}", class: "card-img-top mw-100 mh-100", style: "width: 350px; height: 275px;") %>
      <div class="card-body">
          <h5 class="card-title"><%= item.name %></h5>
          <h6 class="card-subtitle mb-2 text-muted">$ <%= item.price %></h6>
          <p class="card-text"><%= item.description %></p>
          <%= link_to 'Show', item, class: "btn btn-outline-light" %>
          <%= link_to 'Edit', edit_item_path(item), class: "btn btn-outline-light" %>
          <%= link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-outline-light" %>
      </div>
    </div>
  </div>
    <% end %>
  </div>
</div>


<br>

<%= link_to 'New Item', new_item_path %>

app/views/items/new.html.erb
<h1>New Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Back', items_path %>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<div class="card border-dark text-white bg-dark mb-3 mx-auto" style="width: 800px; height: 800px;">
  <%= image_tag("#{@item.image_url}", class: "card-img-top mw-100", style:"height: 600px;") %>
  <div class="card-body">
      <h5 class="card-title"><%= @item.name %></h5>
      <h6 class="card-subtitle mb-2 text-muted">$ <%= @item.price %></h6>
      <p class="card-text"><%= @item.description %></p>
      <%= link_to 'Edit', edit_item_path(@item), class: "btn btn-outline-light" %>
      <%= link_to 'Destroy', @item, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-outline-light" %>
  </div>
</div>

<%= link_to 'Back', items_path %>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark sticky-top">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">EBakery</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="/">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/menus/new">Add Menu</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/items/new">Add Item</a>
        </li>
      </ul>
      <%= form_tag items_path, class: "d-flex", method: :get do %>
        <%= text_field_tag :search, params[:search], class: "form-control", placeholder: "Search" %>
        <%= submit_tag("Search", name: nil, class: "btn btn-outline-success")%>
      <% end %>

      <%# <form class="d-flex" action="/items" method="GET">
        <input class="form-control me-2" name="search" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form> %>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EBakery</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <%= render 'layouts/nav' %>


  <div class="container">
    <div class="row">
      <div class="col pt-4 text-center mx-auto">
        <body>
            <%= yield %>

          <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>
        </body>
      </div>
    </div>
  </div>
</html>

app/views/menus/_form.html.erb
<div class="container">
  <div class="row">
    <div class="col">
      <%= form_with(model: menu) do |form| %>
        <% if menu.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(menu.errors.count, "error") %> prohibited this menu from being saved:</h2>

          <ul>
            <% menu.errors.each do |error| %>
              <li><%= error.full_message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

  <div class="md06 pb-3">
    <%= form.text_field :name, class: "form-control", placeholder: "name" %>
  </div>

  <div class="actions pt-3 pb-3">
    <%= form.submit %>
  </div>
<% end %>

    </div>
  </div>
</div>

app/views/menus/edit.html.erb
<h1>Editing Menu</h1>

<%= render 'form', menu: @menu %>

<%= link_to 'Show', @menu %> |
<%= link_to 'Back', menus_path %>

app/views/menus/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Menus</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @menus.each do |menu| %>
      <tr>
        <td><%= menu.name %></td>
        <td><%= link_to 'Show', menu %></td>
        <td><%= link_to 'Edit', edit_menu_path(menu) %></td>
        <td><%= link_to 'Destroy', menu, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Menu', new_menu_path %>

app/views/menus/new.html.erb
<h1>New Menu</h1>

<%= render 'form', menu: @menu %>

<%= link_to 'Back', menus_path %>

app/views/menus/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @menu.name %>
</p>

<%= link_to 'Edit', edit_menu_path(@menu) %> |
<%= link_to 'Back', menus_path %>

app/views/pages/home.html.erb
<h1>Welcome to EBakery</h1>

<%= image_tag("woman-beside-bottles-and-cupboard-1089570.jpg", class: "img-fluid border border-dark shadow-lg p-3 mb-5 bg-white rounded ") %>


<%= button_to "View Menu", items_path, method: :get, class: "btn btn-secondary btn-lg border border-dark rounded"%>